### ISSUE TITLE
Last list item if commented will be indented two spaces after formatting

### ISSUE THREAD

**Issue by djgoku** [google/yamlfmt#112]
Originally posted here: https://github.com/google/yamlfmt/issues/74#issuecomment-1505882709

input yaml:
```
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
    hooks:
      # - id: infracost_breakdown
      - id: terraform_fmt
      # - id: terraform_providers_lock
      - id: terraform_validate
      # - id: terrascan
```
output yaml:
```
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
    hooks:
      # - id: infracost_breakdown
      - id: terraform_fmt
      # - id: terraform_providers_lock
      - id: terraform_validate
        # - id: terrascan <-- two leading spaces
```
