### ISSUE TITLE
Issues with helm templates

### ISSUE THREAD

**Issue by inssein** [google/yamlfmt#114]
Might be out of scope for this project, but I was trying to use `yamlfmt` on our charts repository and it ran into all sorts of errors with the templates.

Example of error:
```
configuration-service/templates/postgres.yaml: yaml: did not find expected node content
```

**Comment by braydonk** [comment]
Hi @inssein thanks for opening an issue. Admittedly I'm very outside of the Kubernetes world so I can't say confidently why this wouldn't work. I don't know much about helm charting.

I think it's in scope for the project, I would really love it to work because helm charts are such a heavy spot where people use lots of yaml.

It would be a big help if you could post an example of a helm chart that failed (with any info redacted of course) so I could look into it and see if it's something that's fixable. Perhaps helm charts use a different yaml syntax or something that I don't know about.

**Comment by inssein** [comment]
@braydonk for sure, here is an example I took from our repository:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimiter-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  config.yaml: |
    ---
    domain: test
    descriptors:
      - key: foo
        rate_limit:
          unit: minute
          requests_per_unit: 1000000000
```

When I run this file through `yamlfmt`, I get:
```
2023/05/15 10:03:03 encountered the following formatting errors:
[redacted]/configmap-ratelimiter.yaml: yaml: line 5: did not find expected node content
```
