### ISSUE TITLE
Exclude is still a little bit wonky

### ISSUE THREAD

**Issue by esn89** [google/yamlfmt#139]
I have `yamlfmt` installed via nvim mason and it resides in `~/.local/share/nvim/mason/bin`.

I have a file named `env-config.yaml` located in

```
/Users/esn89/Documents/Projects/helm-charts/application.git/develop/services/superapp/templates
```

which looks like this:

```yaml
apiVersion: v1
data:
  PROJECT: {{ .Values.project }}
  JOB_NAME: {{ .Values.jobName }}

kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
```

I ran `~/.local/share/nvim/mason/bin/yamlfmt -conf ~/.config/nvim/.yamlfmt env-config.yaml ` and it formats my file to look like this:

```yaml
---
apiVersion: v1
data:
  PROJECT: {? {.Values.project: ''} : ''}
  JOB_NAME: {? {.Values.jobName: ''} : ''}
kind: ConfigMap
metadata:
  namespace: {? {.Values.namespace: ''} : ''}
```

These is really strange, as I have set the `**template/*.yaml` path to be excluded.

My `~/.config/nvim/.yamlfmt` looks as follows:

```yaml
doublestar: true
exclude:
  - "/Users/esn89/Documents/Projects/**/templates/*.yaml"
  - "/Users/esn89/Documents/Projects/**/.gitlab-ci.yml"
formatter:
  type: basic
  indent: 2
  include_document_start: true
```

Any ideas?

**Comment by braydonk** [comment]
I think this is coming down to excludes being absolute paths again. When passing the path into the argument, then the included path is `env-config.yaml` which according to doublestar does not match `/Users/esn89/Documents/Projects/**/templates/*.yaml`.

I still don't handle mixed absolute path/relative path excludes well. I [note it in the docs](https://github.com/google/yamlfmt/blob/main/docs/metadata.md#how-to-specify). Likely what I should do is check whether either one is an absolute path, and if one is then convert the other. But I would need to test that thoroughly to make sure it works in all scenarios.

Either way I can see how this sucks for the editor plugin use-case; usually the content is just passed to `yamlfmt` through `stdin`, with no path-awareness other than the current working directory. I'll try to find a way to address this too.

As a short-term workaround, you can use [ignore metadata](https://github.com/google/yamlfmt/blob/main/docs/metadata.md#how-to-specify) on this file, which I know is not ideal but still should work for this usecase.

**Comment by esn89** [comment]
I see.   So from what I've read the paths need to be specified as _relative_ to where the yamlfmt binary is, right?

https://github.com/google/yamlfmt/blob/main/docs/paths.md#include-and-exclude

**Comment by braydonk** [comment]
Not relative to where the `yamlfmt` binary is, rather relative to the current working directory that `yamlfmt` is run from, which in most cases would be the project directory, or in neovim the directory that you have open (I think).

Starting with `**` can help here, since that just means "any directory/directories appearing until the next thing in the match".

**Comment by esn89** [comment]
So something like this, @braydonk ?

```yaml
doublestar: true
exclude:
  - "**/templates/*.yaml"
  - "/Users/esn/Documents/Projects/**/.gitlab-ci.yml"
formatter:
  type: basic
  indent: 2
  include_document_start: true
```
