### ISSUE TITLE
Request: `indent` being respected beyond top level

### ISSUE THREAD

**Issue by jamesbraza** [google/yamlfmt#142]
The below:

```yaml
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-byte-order-marker
          - id: check-docstring-first
          - id: requirements-txt-fixer
            description: >-
                Sorts entries in requirements.txt and removes incorrect entry
                for `pkg-resources==0.0.0`.
```

With `-formatter=indent=4,scan_folded_as_literal=true` being passed to `yamlfmt` gets corrected to:

```yaml
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-byte-order-marker
        - id: check-docstring-first
        - id: requirements-txt-fixer
          description: >-
            Sorts entries in requirements.txt and removes incorrect entry
            for `pkg-resources==0.0.0`.
```

We can see the top level 4-space indent was preserved, but not the nested levels beyond that.

Can we make `indent` be recursive?
