### ISSUE TITLE
Feature request: allow to retain some empty lines

### ISSUE THREAD

**Issue by doublethink13** [google/yamlfmt#152]
Imagine I have this file:

```yaml
---
# https://taskfile.dev/styleguide/

version: "3"

env:
  PYTHON_VERSION: "3.11.2"

tasks:
  setup-python-interpreter:
    cmds:
      - pyenv install --skip-existing {{.PYTHON_VERSION}}
      - pyenv local {{.PYTHON_VERSION}}
    desc: uses pyenv to locally install python
  
  setup-venv:
    cmds:
      - python -m venv venv
    desc: sets up python venv

```

As far as I understand, I can do one of two things:
- Either set `retain_line_breaks` to `true`, which means I could end up with extra lines even after formatting, for example:
```yaml
---
# https://taskfile.dev/styleguide/





version: "3"

env:
  PYTHON_VERSION: "3.11.2"

tasks:
  setup-python-interpreter:
    cmds:
      - pyenv install --skip-existing {{.PYTHON_VERSION}}
      - pyenv local {{.PYTHON_VERSION}}
    desc: uses pyenv to locally install python



  setup-venv:
    cmds:
      - python -m venv venv
    desc: sets up python venv
```
- Or I could set `retain_line_breaks` to `false`, which means I only end up with:
```yaml
---
# https://taskfile.dev/styleguide/
version: "3"
env:
  PYTHON_VERSION: "3.11.2"
tasks:
  setup-python-interpreter:
    cmds:
      - pyenv install --skip-existing {{.PYTHON_VERSION}}
      - pyenv local {{.PYTHON_VERSION}}
    desc: uses pyenv to locally install python
  setup-venv:
    cmds:
      - python -m venv venv
    desc: sets up python venv
```

I would like to be able to set `retain_line_breaks` to a number, for example, 1, so that I can have a clear separation of one line, but never more, like the Taskfile style guide [suggests](https://taskfile.dev/styleguide/#add-spaces-between-tasks), and I personally agree.

If this is something relevant I could try to have a look if you are accepting contributors :slightly_smiling_face:
