### ISSUE TITLE
yamlfmt does not respect `excldue`

### ISSUE THREAD

**Issue by chenrui333** [google/yamlfmt#154]
👋 I am trying to introduce yamlfmt into atlantis project, but whenever I run with the following config file

```
exclude:
  - .circleci/config.yml
  - .github/**
```

the yamlfmt still tries to fmt the `.github/workflow/*.yml` files, did I miss anything? Thanks!

relates to https://github.com/runatlantis/atlantis/pull/4123

**Comment by braydonk** [comment]
Hi @chenrui333 thanks for opening an issue.

Is that your full config? To use `**` you need to enable the configuration `doublestar: true`. Once I do that, what you have works for me.
```yaml
doublestar: true
include:
  - "./**/*.{yaml,yml}"
exclude:
  - ".github/**"
```
