### ISSUE TITLE
pyproject.toml integration

### ISSUE THREAD

**Issue by Ruhrozz** [google/yamlfmt#205]
Could you implement pyproject.toml integration for python projects?

pyproject.toml should look like:
```toml
[tool.yamlfmt.formatter]                                                                                                
retain_line_breaks_single = true                                                                                                                                                                               
```
