### ISSUE TITLE
Unquoting certain strings changes the data type of the field

### ISSUE THREAD

**Issue by jgopel** [google/yamlfmt#209]
Reproduction steps:
1) Create a yaml file with a key that is a special value ("true", "false", "yes", "no", etc).
2) Run `yamlfmt` on the file.

Expected outcome: Quotes are left in place to keep the type of the value as a string, not, eg, a bool.
Actual outcome: Quotes are removed and the type changes.

This is problematic as it breaks things in certain contxt. e.g. https://stackoverflow.com/questions/46233297/docker-compose-yml-why-does-restart-no-have-to-have-quotation-marks - `docker compose` requires `restart` to retain quotes for `"no"` as it does not support booleans for that field.

**Comment by braydonk** [comment]
Hi @jgopel thanks for opening an issue.

I think I'll need more information to reproduce. Right now I can't seem to, at least off of `main`. 
```
braydonk@bk:~/Git/yamlfmt$ cat ./tmp/a.yaml 
"yes": "yes"
"no": "no"
"true": "true"
"false": "false"
a:
 b: 1
braydonk@bk:~/Git/yamlfmt$ go run ./cmd/yamlfmt ./tmp/a.yaml 
braydonk@bk:~/Git/yamlfmt$ cat ./tmp/a.yaml 
"yes": "yes"
"no": "no"
"true": "true"
"false": "false"
a:
  b: 1
```
(In the first example `b` only has one space indent and on the second it has two, this is the trick I always use to prove to myself it ran on the file)

My repro attempt was done with an empty yamlfmt config. Perhaps this issue is only reproducable with some specific setting on. Could you please provide:
* The OS you're running on
* The version of `yamlfmt`
* Your `yamlfmt` config file
* An example yaml file you have that can reproduce the issue
