### ISSUE TITLE
Feat Request: Option to set and enforce a specific number of line breaks

### ISSUE THREAD

**Issue by badrobit** [google/yamlfmt#210]
The current formatter will allow you to keep as many or as few line breaks if they already exist between entries. I was hoping by setting `retain_line_breaks_single: true` it would also add line breaks if they didn't exist already.

The output of the tool would be more uniform (but cause bigger diffs) if it were to set the number of line breaks and add/remove them until at the user defined (or default) setting. 

e.g. 
```yaml
formatter:
  type: basic
  line_breaks: 1 # <-- New Suggested setting
```

it could default to zero which would remove them all which is the current behavior then when a value is set it would add/trim the found line breaks to align with the user defined value.

## Example: 

Input: 
```
a: 
    b_a: value
    b_b: value2
    a-b: 
      - x
      - y
      - z
    a-c: 
      - x
      - y
      - z
      -
```

output: 
```yaml
a:  # I am unsure if a newline after this but before (b_a) makes sense 

    b_a: value
    b_b: value2 # I am unsure if a newline after this but before (a_b) makes sense 

    a_b: 
      - x
      - y
      - z

    a_c: 
      - x
      - y
      - z
```

**Comment by braydonk** [comment]
Hi @badrobit thanks for the feature request.

I have had requests for similar features before, but your version sounds a bit different and if I'm understanding correctly is the first I've ever heard of anyone having a use case like this.
Do you mean you'd like a feature Like this?  
Before:
```
a: 1
b: 2
c: 3
```
After:
```
a: 1

b: 2

c: 3
```
If so, I suppose I could add something like that but it's definitely the first I've heard of someone wanting something like this.

I have had requests for a feature like `retain_max_line_breaks` such that with a setting like `retain_max_line_breaks: 2` this:
```
a: 1



b: 2
```
Would become:
```
a: 1


b: 2
```
That feature would be relatively easy to implement, but it sounds different than what you're asking for so I want to make sure.

**Comment by badrobit** [comment]
I think it is a weird mix (I know why can it not just be simple). I think it would be based on parent grouping so if say you had the following: 

```yaml
a: 
	b_a: value
    b_b: value2
	a-b: 
	  - x
	  - y
	  - z
	a-c: 
	  - x
	  - y
	  - z
```

you would get the following out (assuming line separation is set to 1: 
```yaml
a:  # I am unsure if a newline after this but before (b_a) makes sense 
	b_a: value
    b_b: value2 # I am unsure if a newline after this but before (a_b) makes sense 
	a_b: 
	  - x
	  - y
	  - z

	a_c: 
	  - x
	  - y
	  - z
```

I think what I am asking for is if at each level (with children) it is separated. I think the key part is the children as it would be a bit weird and less readable if you put a line between every entry. The most common example I can think of that I tend to do this with is the `.pre-commit-config.yaml` where I will add a new line between each repo listed

**Comment by z2oh** [comment]
I'd like to echo this feature request. I'm looking to format some GitHub actions workflows with lengthy, multi-line values; added whitespace makes them much easier to read.

**Comment by JonathanAtCenterEdge** [comment]
+1

Large GHA workflow yaml's or large k8s deployment manifests are pretty hard to read without line breaks

**Comment by braydonk** [comment]
I think the feature as described in the original post and in [this comment](https://github.com/google/yamlfmt/issues/210#issuecomment-2375155543) is infeasible. I personally can't foresee a consistent way to apply that rule in YAML programatically, especially given that the example in the clarifying comment above has the newlines applied in inconsistent ways in the AST. 

YAML is such a freeform language that it ends up being down to personal opinion and context when to/not to put a line break. I think it shouldn't be up to a formatter to do something like [this](https://github.com/google/yamlfmt/issues/210#issuecomment-2375155543), and it should be the decision of the YAML author exactly where convenient line breaks should go.

I'm going to close this issue because I'm pretty sure I'm not going to be able to implement it. I'm not sure if any other YAML formatters have done something like this. If any have, feel free to link it here and I can take a look to see if there's something I'm missing and can maybe take inspiration from.

**Comment by z2oh** [comment]
Fair enough. If I get some time I may look into trying to implement this. I don't think any other YAML formatters do this (I've done some light searching here, as enforced whitespace is the only feature I want from a YAML formatter).

Naively, I think what I want is just the ability to add `N` newlines between each node of a [block sequence](https://yaml.org/spec/1.2.2/#rule-l+block-sequence), but I would need to give this more thought to be confident in that.

**Comment by braydonk** [comment]
If adding newlines after a block sequence is the extent of it, that would be pretty reasonably simple to implement and is consistently detectable while encoding. The original proposal sounded more in-depth, with some ambiguous circumstances that would be non-trivial to detect while encoding.

**Comment by z2oh** [comment]
> adding newlines after a block sequence is the extent of it

_Between_ nodes of a block sequence would be even better, but just after block sequence would very useful for me. To give examples of what I'm hoping for (independent of the original proposal)

Input:
```
a: 
    b_a: value
    b_b: value2
    a-b: 
        - x
        - y
        - z
    a-c: 
        - x
        - y
        - z
b:
    - x
```


I would love to be able to get any of these as outputs:
```
a:
    b_a: value

    b_b: value2

    a_b:
      - x

      - y

      - z

    a_c: 
      - x

      - y

      - z

b:
    - x
```
or
```
a: 
    b_a: value
    b_b: value2

    a-b: 
        - x
        - y
        - z

    a-c: 
        - x
        - y
        - z

b:
    - x
```
or
```
a: 
    b_a: value
    b_b: value2
    a-b:
        - x

        - y

        - z

    a-c:
        - x

        - y

        - z

b:
    - x
```
