### ISSUE TITLE
Format with padding

### ISSUE THREAD

**Issue by ccoVeille** [google/yamlfmt#234]
I would like to be able to use yamlfmt to bring this

```yaml
vars:
  FOO_USER: "user"
  FOO_PASSWORD: "pass"
  FOO_ADD: "localhost:9000"
  FOO_DB: "whatever"
```

And do this

```yaml
vars:
  FOO_USER:     "user"
  FOO_PASSWORD: "pass"
  FOO_ADD:      "localhost:9000"
  FOO_DB:       "whatever"
```

We had an interesting discussion in #232
