### ISSUE TITLE
bug: when document start have comments before, formatter moves it on top of the file.

### ISSUE THREAD

**Issue by vveliev** [google/yamlfmt#236]
When yaml includes comments before document start formatters moves it on the top.

Here is the example yaml file:

```yml
# -*- coding: utf-8 -*-
# vim: ft=yaml
# yamllint disable rule:truthy
---
name: ci-pipeline

on:
  pull_request:
  push:
    branches: [main]
```

when using formatter with this options I'm not expecting any changes
`-formatter include_document_start=true,retain_line_breaks_single=true`

instead I'm getting this:
```yml
---
# -*- coding: utf-8 -*-
# vim: ft=yaml
# yamllint disable rule:truthy
name: ci-pipeline

on:
  pull_request:
  push:
    branches: [main]
```

<img width="882" alt="Image" src="https://github.com/user-attachments/assets/2f78ecd7-8c47-4cbf-b062-8e669a22f1b3" />
