### ISSUE TITLE
Support for "3" as an indent value

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [google/yamlfmt#237]
After fifteen years of using it, I can't believe my insane choice has basically just worked with everything I've tried it with ... until now.

Finally, a tool that doesn't handle threesp indentation well. I'm almost thankful, I've been waiting for this for so long.

So, at the moment, as far as I can tell, there's no difference between `indent: 2` and `indent: 3`. It seems to be a noop. Unsure if this is a side-effect of some other behaviour, or if the value is intentionally constrained to `2` or `4`?

Ideally, if you were bored enough to go out of your way to implement a feature that probably literally nobody but me would use, I'd like to see the `-` for list-items embedded _in_ the indentation, instead of _after_ it (so, not *quite* indentless arrays, but array-delimeter-recesses-into-indentation, which is indistinguishable for twosp indents):

```yaml
 - name: secure ssh configuration part 2
   become: true
   lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
   loop:
    - {regexp: '^AllowGroups', line: 'AllowGroups sshusers'}
    - {regexp: '^ClientAliveCountMax', line: 'ClientAliveCountMax 0'}
    - {regexp: '^ClientAliveInterval', line: 'ClientAliveInterval 300'}
    - {regexp: '^ListenAddress', line: 'ListenAddress 0.0.0.0'}
   ...
    - {regexp: '^LoginGraceTime', line: 'LoginGraceTime 30'}
   notify: restart ssh service
```

Anyway, I'm not delusional enough to see extra implementation work to go into this for me; I leave this Issue primiarly as a reminder to myself incase I get annoyed enough to come patch it myself ... and as a battle-cry for those strong few of us using the objectively best, middle-ground indentation setting. 💪 (Just sayin'.)

**Comment by braydonk** [comment]
Hi @ELLIOTTCABLE thanks for opening an issue!

I just tried to reproduce the 3 space indentation issue, but when I set `indent: 3` it seems to have the desired effect. I adapted the yaml example you posted just out of need for an example to run on:
```yaml
name: 
become: true
lineinfile:
  dest: /etc/ssh/sshd_config
  regexp: "{{ item.regexp }}"
  line: "{{ item.line }}"
loop:
- {regexp: '^AllowGroups', line: 'AllowGroups sshusers'}
- {regexp: '^ClientAliveCountMax', line: 'ClientAliveCountMax 0'}
- {regexp: '^ClientAliveInterval', line: 'ClientAliveInterval 300'}
- {regexp: '^ListenAddress', line: 'ListenAddress 0.0.0.0'}
```
Then ran yamlfmt like so:
```
$ go run ./cmd/yamlfmt -formatter indent=3 tmp/a.yaml
$ cat tmp/a.yaml
name:
become: true
lineinfile:
   dest: /etc/ssh/sshd_config
   regexp: "{{ item.regexp }}"
   line: "{{ item.line }}"
loop:
   - {regexp: '^AllowGroups', line: 'AllowGroups sshusers'}
   - {regexp: '^ClientAliveCountMax', line: 'ClientAliveCountMax 0'}
   - {regexp: '^ClientAliveInterval', line: 'ClientAliveInterval 300'}
   - {regexp: '^ListenAddress', line: 'ListenAddress 0.0.0.0'}
```
I also tried running it with the following `yamlfmt` config file:
```yaml
formatter:
  indent: 3
```
And the result was the same. Perhaps this is a platform difference somehow, or an accidental misconfiguration? (You can troubleshoot configuration stuff with [debug logging](https://github.com/google/yamlfmt/blob/main/docs/command-usage.md#debug-logging)).

---

In the case of alternative indentation for arrays, believe it or not [the first thing I tried actually worked](https://github.com/braydonk/yaml/pull/19/files). I should be able to get it added to the yamlfmt in the next release.
