### ISSUE TITLE
Issue when anchor is used as a key

### ISSUE THREAD

**Issue by nilcolor** [google/yamlfmt#242]
Imagine the following YAML snippet:

```yaml
x-config-values:
  x-domain-ext: &domain-ext www.example.com
  x-domain-int: &domain-int example.local

ingresses:
  *domain-ext :
    name: example
    hosts:
      - domainName: *domain-ext
        paths:
          - path: "/"
            pathType: Prefix

  *domain-int :
    name: example-local
    hosts:
      - paths:
          - path: "/api"
            pathType: Prefix
```
This is valid YAML that resolves to:
```yaml
x-config-values:
  x-domain-ext: www.example.com
  x-domain-int: example.local
ingresses:
  www.example.com:
    name: example
    hosts:
      - domainName: www.example.com
        paths:
          - path: /
            pathType: Prefix
  example.local:
    name: example-local
    hosts:
      - paths:
          - path: /api
            pathType: Prefix
```
However, if `yamlfmt` is run on the initial snippet, it will replace anchors like `*domain-ext :` with `*domain-ext:`, which still looks fine but is no longer valid YAML from other tools' perspectives.
I was not able to find any settings to prevent this. Is there any? Can this be added as a flag? Tbh I'm not even sure how this type of anchors is named...
