### ISSUE TITLE
yamlfmt doesn't output any error or status when changing files to windows line-endings

### ISSUE THREAD

**Issue by r-downing** [google/yamlfmt#244]
If I enable the following two hooks (mixed-line-ending) and (yamlfmt) with default config on Windows, the mixed-line-ending will convert everything to lf, but then the yamlfmt will convert it back, but exit successfully.

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
```

If I use `dos2unix` to modify a yaml file and just run the yamlfmt hook, it will change the line endings but still exit successfully.

This made it difficult to figure out what was going on, until I realized I needed a config file for yamlfmt to use lf line endings. But still, it feels like yamlfmt should have some status-output when it is in fact modifying the content of files.
