### ISSUE TITLE
Unstable formatting of comments

### ISSUE THREAD

**Issue by denik** [google/yamlfmt#253]
This file when formatted alternates back and forth between 2 representations:

```
artifacts:
  my_artifact:
  # build
```

```
% cat t.yaml && go tool yamlfmt -v t.yaml && cat t.yaml && go tool yamlfmt -v t.yaml && cat t.yaml
artifacts:
  my_artifact:
  # build
The following files were modified:
t.yaml
artifacts:
  my_artifact:
# build
The following files were modified:
t.yaml
artifacts:
  my_artifact:
  # build
```

Version: v0.17.0

Config
```
formatter:
  type: basic
  retain_line_breaks_single: true
  trim_trailing_whitespace: true
  disable_alias_key_correction: true
  scan_folded_as_literal: true
  drop_merge_tag: true
```
