### ISSUE TITLE
Incorrect comment movement for groups of array items

### ISSUE THREAD

**Issue by robbat2** [google/yamlfmt#255]
I'd like to use comments to group sets of entries in an array together - the comment should be at the same level as the `-` for the entry; but yamlfmt keeps indenting or moving it, in consistent ways.

There also doesn't seem to be any docs saying what the expected indentation pattern is.

Testcase 1:
```
---
parent:
  key:
    - a: 1
      b: 2

    # Group comment
    - &anchor
      a: 2
      b: 3
    - a: 4
      b: 5
```

Result 1:
```
$ yamlfmt  -dry test1.yaml
test1.yaml:
  ---                  ---
  parent:              parent:
    key:                 key:
      - a: 1               - a: 1
        b: 2                 b: 2
-
-     # Group comment
      - &anchor            - &anchor
+                            # Group comment
        a: 2                 a: 2
-       b: 3                 b: 3
      - a: 4               - a: 4
-       b: 5                 b: 5
```

Testcase 2:
```
---
key:
  # <group 1>
  - x: a
    b: 1
  - y: foo
    b: bar
  # </group 1>

  # <group 2>
  - z: ax
    b: 1
  - ab: something
    b: 1
  # </group 2>
```

Result 2:
```
$ yamlfmt -dry test2.yaml
test2.yaml:
  ---                ---
  key:               key:
    # <group 1>        # <group 1>
    - x: a             - x: a
      b: 1               b: 1
    - y: foo           - y: foo
      b: bar             b: bar
    # </group 1>       # </group 1>

    # <group 2>        # <group 2>
    - z: ax            - z: ax
      b: 1               b: 1
    - ab: something    - ab: something
      b: 1               b: 1
-   # </group 2>         # </group 2>
```
