### ISSUE TITLE
Difficult to comment out lines in a yaml file

### ISSUE THREAD

**Issue by asmeurer** [google/yamlfmt#258]
Suppose I have a yaml file like

```yaml
a:
  - b: 1
    c: 2
  - d: 1
    e: 2
  - f: 1
    g: 2
  - h: 1
    i: 2 
```

and I try to comment out some of the entries:

```yaml
a:
  - b: 1
    c: 2
  # - d: 1
  #   e: 2
  - f: 1
    g: 2
  # - h: 1
  #   i: 2
```

yamlfmt will now unindent the final commented out lines

```yaml
a:
  - b: 1
    c: 2
  # - d: 1
  #   e: 2
  - f: 1
    g: 2
# - h: 1
#   i: 2
```

This behavior makes it difficult to comment out lines in a yaml file because their uncommented indentation is not preserved. 

It would be nice to have an option to disable reindentation of comment lines.
