### ISSUE TITLE
Retain line breaks

### ISSUE THREAD

**Issue by braydonk** [google/yamlfmt#27]
Sometimes yaml blocks will have a line break between them for human readability, for example:
```
block_a:
  b: "some stuff"

block_b:
  a: "some more info"
```
Today, this will end up being formatted like this:
```
block_a:
  b: "some stuff"
block_b:
  a: "some more info"
```
It would be great not to remove these if possible.
