### ISSUE TITLE
yamlfmt insert blank line between commented line

### ISSUE THREAD

**Issue by sharuzzaman** [google/yamlfmt#34]
I have the following YAML:

```
---
Resources:
  ElasticBeanstalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      #NotificationARNs: 
      #  - String
      #Parameters: 
      #  Key : Value
      #Tags: 
      #  - Tag
      TemplateURL: https://examplebucket.s3.ap-southeast-1.amazonaws.com/example-file.json
      TimeoutInMinutes: 5
```

after formatting, each commented line will have a blank line inserted, becoming:

```
Resources:
  ElasticBeanstalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      #NotificationARNs: 

      #  - String

      #Parameters: 

      #  Key : Value

      #Tags: 

      #  - Tag
      TemplateURL: https://examplebucket.s3.ap-southeast-1.amazonaws.com/example-file.json
      TimeoutInMinutes: 5
```

I don't see any option to configure the formatter so that it does not include a blank line after each comment.

Thank you.

**Comment by braydonk** [comment]
Hi @sharuzzaman,

Unfortunately at this time there aren't a ton of configuration options, so you wouldn't be able to configure a behaviour like this for the time being.

However, I'm unable to reproduce this behaviour locally at the moment. I tried copying the yaml from the first block into a file on its own and it did not insert the newlines as you've mentioned. 

x.yaml: 
```yaml
---
Resources:
  ElasticBeanstalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      #NotificationARNs: 
      #  - String
      #Parameters: 
      #  Key : Value
      #Tags: 
      #  - Tag
      TemplateURL: https://examplebucket.s3.ap-southeast-1.amazonaws.com/example-file.json
      TimeoutInMinutes: 5
```
Piping it into `stdin`:
```bash
braydonk@bk:~/Git/yamlfmt$ cat x.yaml | yamlfmt -dry
dry run produced no output
```

There's a chance this is a platform issue. What operating system are you on?
