### ISSUE TITLE
Emoji convert to Unicode codepoints

### ISSUE THREAD

**Issue by guitarrapc** [google/yamlfmt#38]
## Description

yamlfmt convert emoji to Unicode codepoints.
This is breaking change to yaml.

## Reproduce steps

1. prepare yaml.

```yaml
ascii: this is acsii
# https://emojipedia.org/smiling-face-with-smiling-eyes/ https://codepoints.net/U+1F60A
# https://emojipedia.org/party-popper/ https://codepoints.net/U+1F389
emoji: 😊 🎉
```

2. Run yamlfmt.
3. See changed. Emoji convert to it's Unicode.

```yaml
ascii: this is acsii
# https://emojipedia.org/smiling-face-with-smiling-eyes/ https://codepoints.net/U+1F60A
# https://emojipedia.org/party-popper/ https://codepoints.net/U+1F389
emoji: "\U0001F60A \U0001F389"
```

## -dry diff

```bash
$ ls
foo.yaml

$ yamlfmt -dry
foo.yaml:
  ascii: this is acsii
  # https://emojipedia.org/smiling-face-with-smiling-eyes/ https://codepoints.net/U+1F60A
  # https://emojipedia.org/party-popper/ https://codepoints.net/U+1F389
- emoji: 😊 🎉
+ emoji: "\U0001F60A \U0001F389"
```

## Version Info

* yamlfmt v0.3.0
* OS: Windows 10 and 11
