### ISSUE TITLE
Config option to reject anchors and aliases?

### ISSUE THREAD

**Issue by imjasonh** [google/yamlfmt#51]
I'd like to be able to ensure a YAML document doesn't include any anchors or aliases: https://yaml.org/spec/1.2.2/#3222-anchors-and-aliases, e.g.:

```
definitions: 
  steps:
    - step: &build-test
        name: Build and test
        script:
          - mvn package
        artifacts:
          - target/**

pipelines:
  branches:
    develop:
      - step: *build-test
    main:
      - step: *build-test
```

(from here: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/)

It doesn't look like that's currently possible with this tool, but would you accept a PR to add it?

Practically speaking I think this would look like checking for `Node.Kind == yaml.AliasNode`, or `Node.Anchor != ""`, defined in the [`Node`](https://pkg.go.dev/gopkg.in/yaml.v3#Node) type. The option would probably default to `false` for compatibility.
