### ISSUE TITLE
Folded block scalars with whitespace at the end causes problems

### ISSUE THREAD

**Issue by braydonk** [google/yamlfmt#86]
While investigating #84 I realized that the yaml library parses weirdly when there is whitespace at the end of lines in a folded block scalar. 

When `scan_folded_as_literal: false`, you get the original bug shown in issue 84. 

When `scan_folded_as_literal: true`, you get the following with the same input:
```yaml
Foobar:
  baz: "Lorem Ipsum is simply dummy text of the printing_and_typesetting industry.
    \n#magic___^_^___line\n"
Foobaz:
  baz: "foobar"
```

Will need to figure out why whitespace at the end of the line causes the library to think it's not printable.
